# config/secrets.yml

development:
  clover_access_token: <%= ENV['CLOVER_ACCESS_TOKEN_DEV'] %>
  clover_merchant_id: <%= ENV['CLOVER_MERCHANT_ID_DEV'] %>
  clover_device_id: <%= ENV['CLOVER_DEVICE_ID_DEV'] %>

test:
  clover_access_token: <%= ENV['CLOVER_ACCESS_TOKEN_TEST'] %>
  clover_merchant_id: <%= ENV['CLOVER_MERCHANT_ID_TEST'] %>
  clover_device_id: <%= ENV['CLOVER_DEVICE_ID_TEST'] %>

production:
  clover_access_token: <%= ENV['CLOVER_ACCESS_TOKEN_PROD'] %>
  clover_merchant_id: <%= ENV['CLOVER_MERCHANT_ID_PROD'] %>
  clover_device_id: <%= ENV['CLOVER_DEVICE_ID_PROD'] %>
